development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion-stats_development
  pool: 5
  username: root
  password: password

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion-stats_test
  pool: 5
  username: root
  password: password
  
ci:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: myapp_test
  pool: 5
  username: root  

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion-stats_production
  pool: 5
  username: root
  password: password