development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion_stats_development
  pool: 5
  username: root

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion_stats_test
  pool: 5
  username: root

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion_stats_production
  pool: 5
  username: root
