development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion-stats_development
  pool: 25
  username: root

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion-stats_test
  pool: 25
  username: root

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subversion-stats_production
  pool: 25
  username: root
